[workspace]
members = [
    "rust-by-example/constants",
    "rust-by-example/enums",
    "rust-by-example/ferris_says",
    "rust-by-example/first-application",
    "rust-by-example/hello-world", "rust-in-action/ch3/filebasics", "rust-in-action/ch3/fileresult",
]
